### ISSUE TITLE
aanpassen indexeerstap naar lokaal

### ISSUE THREAD

**Issue by susannelh** [tigistzn/tigistzn#8]
https://docs.llamaindex.ai/en/stable/examples/vector_stores/SimpleIndexDemoLlama2/

**Comment by tigistzn** [comment]
@susannelh  kunnen samen naar deze kijken als je wil? Oguzhan en ik hebben net besproken wat dit in zou houden.

**Comment by susannelh** [comment]
Wordt nu met model van openai gedaan, moet met ander model
HuggingFace --> best RAG index models hugging face lijstje
model downloaden op eigen laptop (kleine)
gaat om technische principe werkend krijgen

**Comment by susannelh** [comment]
https://huggingface.co/jinaai/jina-embeddings-v2-small-en
Staat redelijk hoog in HF-leaderbord 
https://huggingface.co/spaces/mteb/leaderboard

Werkt als embedding model --> geimplementeerd in indexing.py --> PR staat klaar.
